### ISSUE TITLE
Error creating DATABASECHANGELOG table

### ISSUE THREAD

**Issue by jaalvarezuria** [liquibase/liquibase-bigquery#223]
Hi,

I´m trying to execute some changelogs and I´ve de following error when liquidbase tries to create its tables:

[2023-11-23 10:47:49] INFO [liquibase.command] Command execution complete
[2023-11-23 10:47:49] SEVERE [liquibase.integration] [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Type not found: VARCHAR at [1:36] [Failed SQL: (100032) CREATE TABLE DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED datetime NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))]
  - Caused by: 400 Bad Request
POST https://bigquery.googleapis.com/bigquery/v2/projects/my-project/queries
***
  "code": 400,
  "errors": [
    ***
      "domain": "global",
      "location": "q",
      "locationType": "parameter",
      "message": "Type not found: VARCHAR at [1:36]",
      "reason": "invalidQuery"
    ***
  ],
  "message": "Type not found: VARCHAR at [1:36]",
  "status": "INVALID_ARGUMENT"
***
liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Type not found: VARCHAR at [1:36] [Failed SQL: (100032) CREATE TABLE DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED datetime NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))]
	at liquibase.command.CommandScope.execute(CommandScope.java:237)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)

I´m using the liquidbase github action plugin with the following options:

- uses: liquibase-github-actions/update@v4.25.0
        id: updatedb
        name: Update liquibase
        with:
          changelogFile: "db-changelog/config/changelog-master.xml"
          url: "jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;OAuthType=3;ProjectId=my-project;EnableSession=1;DefaultDataset=test_github;Location=europe-west1;QueryDialect=SQL"
          driver: "com.simba.googlebigquery.jdbc42.Driver"

is it maybe liquidbase library github action plugin is using?

Many thanks

**Comment by cuong0993** [comment]
Same issue.
MacOS 14.2.1.
liquibase 4.25.1 from brew
SimbaJDBCDriverforGoogleBigQuery42_1.5.2.1005
liquibase-bigquery-4.25.1.jar

Strange that it work on my Windows :D

**Comment by cuong0993** [comment]
Not sure what configuration caused this. I used classpath for jar files. 
But I can make things work by downloading the liquibase-4.25.1.zip, putting all jar files into the lib folder.

**Comment by gregjay43** [comment]
Same issue:
liquibase/liquibase:4.25.1 docker image
SimbaJDBCDriverforGoogleBigQuery42_1.5.2.1005
liquibase-bigquery-4.25.1.jar

**Comment by carliecope** [comment]
Same issue:
MacOS 14.3.1
liquibase/liquibase:4.25.1 docker image
SimbaJDBCDriverforGoogleBigQuery42_1.5.2.1004
liquibase-bigquery-4.25.1.jar

**Comment by aamanyi-equinix** [comment]
Has this issue been resolved?
