### ISSUE TITLE
Liquibase biguqery 4.28.0 unable to find valid certificate path

### ISSUE THREAD

**Issue by hagarwalppro** [liquibase/liquibase-bigquery#330]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do
not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Debug Output

```
Caused by: liquibase.exception.DatabaseException: Connection could not be created to jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=<project_id>;Location=EU;OAuthType=3;DefaultDataset=himanshu_local_cdc;Timeout=3600; with driver com.simba.googlebigquery.jdbc.Driver.  [Simba][BigQueryJDBCDriver](100004) HttpTransport IO error : Error getting subject token from metadata server: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
	at liquibase.ext.bigquery.database.BigqueryConnection.openConn(BigqueryConnection.java:106)
	at liquibase.ext.bigquery.database.BigqueryConnection.open(BigqueryConnection.java:94)
	at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:32)
	... 30 more
```

### Panic Output

NA
### Steps to Reproduce

1. Use Liquibase 4.28.0 in github action as container
2. Download bigquery jdbc jars and liquibase-bigquery jar and copy it inside `liquibase/lib`
3. Use github action `google-github-actions/auth@v2` to setup WIF, this service account has bigquery admin permissions
4. Finally run liquibase using command below
``` 
liquibase \
            --driver=com.simba.googlebigquery.jdbc.Driver \
            --url="jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=<project_id>;Location=EU;OAuthType=3;DefaultDataset=himanshu_local_cdc;Timeout=3600;" \
            --changeLogFile="changelog.xml" \
            --searchPath="./liquibase/cdc-tables" \
            --log-level debug \
            update
```
5. I have also tried using `encrypt=false;trustServerCertificate=true;` as suggested on post [here](https://forum.liquibase.org/t/unable-to-execute-liquibase-update-on-the-new-mssql-dsetup/7466) even thought it was for sqlserver but error was on the same lines but still same issue.

### Expected Behavior

Liquibase changeset should have got executed

### Actual Behavior

Error below

```
Caused by: liquibase.exception.DatabaseException: Connection could not be created to jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=<project_id>Location=EU;OAuthType=3;DefaultDataset=himanshu_local_cdc;Timeout=3600; with driver com.simba.googlebigquery.jdbc.Driver.  [Simba][BigQueryJDBCDriver](100004) HttpTransport IO error : Error getting subject token from metadata server: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
	at liquibase.ext.bigquery.database.BigqueryConnection.openConn(BigqueryConnection.java:106)
	at liquibase.ext.bigquery.database.BigqueryConnection.open(BigqueryConnection.java:94)
	at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:32)
	... 30 more
```

### References

* #0000

**Comment by joaoheron** [comment]
I'm facing the same issue here. Did you had any success recently @hagarwalppro ?

**Comment by joaoheron** [comment]
I'm facing the same issue here. Have you been able to workaround this issue @hagarwalppro ?

**Comment by joaoheron** [comment]
This problem is still present on version [4.30.0](https://github.com/liquibase/liquibase-bigquery/releases/tag/v4.30.0).
Have you been able to workaround it somehow @hagarwalppro ?

**Comment by KurtYoungTR** [comment]
This is an issue with GitHub Actions. The issue persist even when running Liquibase as an application that is installed on the deployment environment.
